# Generated by Django 2.2.6 on 2019-10-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(max_length=128)),
                ('city_or_town', models.CharField(max_length=128)),
                ('county', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('zip_or_postcode', models.CharField(max_length=128)),
            ],
        ),
    ]
