# Generated by Django 2.2.6 on 2019-11-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191120_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
