# Generated by Django 2.2.6 on 2019-10-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_by',
        ),
    ]
