# Generated by Django 2.2.6 on 2019-11-08 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pubd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
